### ISSUE TITLE
Failed to install 

### ISSUE THREAD

**Issue by pacochair** [chantra/openvpn-mysql-auth#1]
Hi All,

I failed to make the file. Anyone experience like this before?

make  all-recursive
make[1]: Entering directory `/usr/local/vpn-mysql'
Making all in src
make[2]: Entering directory`/usr/local/vpn-mysql/src'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory`/usr/local/vpn-mysql/src'
Making all in tests
make[2]: Entering directory `/usr/local/vpn-mysql/tests'
/bin/sh ../libtool --tag=CC --mode=link gcc  -g -O2 -g -Wall -Werror -L../src  -o testplugin  testplugin.o ../src/.libs/libopenvpn-mysql-auth.a
gcc -g -O2 -g -Wall -Werror -o testplugin testplugin.o  -L/usr/local/vpn-mysql/src ../src/.libs/libopenvpn-mysql-auth.a
../src/.libs/libopenvpn-mysql-auth.a(am_mysql.o): In function`create_expandable_variable_list':
/usr/local/vpn-mysql/src/am_mysql.c:109: undefined reference to `mysql_real_escape_string'
/usr/local/vpn-mysql/src/am_mysql.c:113: undefined reference to`mysql_real_escape_string'
../src/.libs/libopenvpn-mysql-auth.a(am_mysql.o): In function `_am_mysql_query_return_row_0':
/usr/local/vpn-mysql/src/am_mysql.c:289: undefined reference to`mysql_query'
/usr/local/vpn-mysql/src/am_mysql.c:297: undefined reference to `mysql_store_result'
/usr/local/vpn-mysql/src/am_mysql.c:315: undefined reference to`mysql_num_rows'
/usr/local/vpn-mysql/src/am_mysql.c:355: undefined reference to `mysql_free_result'
/usr/local/vpn-mysql/src/am_mysql.c:328: undefined reference to`mysql_num_fields'
/usr/local/vpn-mysql/src/am_mysql.c:334: undefined reference to `mysql_fetch_row'
/usr/local/vpn-mysql/src/am_mysql.c:341: undefined reference to`mysql_fetch_lengths'
/usr/local/vpn-mysql/src/am_mysql.c:305: undefined reference to `mysql_field_count'
/usr/local/vpn-mysql/src/am_mysql.c:311: undefined reference to`mysql_error'
/usr/local/vpn-mysql/src/am_mysql.c:311: undefined reference to `mysql_errno'
/usr/local/vpn-mysql/src/am_mysql.c:293: undefined reference to`mysql_error'
/usr/local/vpn-mysql/src/am_mysql.c:293: undefined reference to `mysql_errno'
/usr/local/vpn-mysql/src/am_mysql.c:338: undefined reference to`mysql_error'
/usr/local/vpn-mysql/src/am_mysql.c:338: undefined reference to `mysql_errno'
../src/.libs/libopenvpn-mysql-auth.a(am_mysql.o): In function`_am_mysql_simple_query':
/usr/local/vpn-mysql/src/am_mysql.c:207: undefined reference to `mysql_query'
/usr/local/vpn-mysql/src/am_mysql.c:211: undefined reference to`mysql_error'
/usr/local/vpn-mysql/src/am_mysql.c:211: undefined reference to `mysql_errno'
/usr/local/vpn-mysql/src/am_mysql.c:215: undefined reference to`mysql_store_result'
/usr/local/vpn-mysql/src/am_mysql.c:235: undefined reference to `mysql_num_rows'
/usr/local/vpn-mysql/src/am_mysql.c:240: undefined reference to`mysql_free_result'
/usr/local/vpn-mysql/src/am_mysql.c:223: undefined reference to `mysql_field_count'
/usr/local/vpn-mysql/src/am_mysql.c:229: undefined reference to`mysql_error'
/usr/local/vpn-mysql/src/am_mysql.c:229: undefined reference to `mysql_errno'
/usr/local/vpn-mysql/src/am_mysql.c:225: undefined reference to`mysql_affected_rows'
../src/.libs/libopenvpn-mysql-auth.a(am_mysql.o): In function `am_mysql_prepare_mysql':
/usr/local/vpn-mysql/src/am_mysql.c:160: undefined reference to`mysql_init'
/usr/local/vpn-mysql/src/am_mysql.c:166: undefined reference to `mysql_options'
/usr/local/vpn-mysql/src/am_mysql.c:170: undefined reference to`mysql_real_connect'
/usr/local/vpn-mysql/src/am_mysql.c:171: undefined reference to `mysql_error'
/usr/local/vpn-mysql/src/am_mysql.c:171: undefined reference to`mysql_errno'
../src/.libs/libopenvpn-mysql-auth.a(am_mysql.o): In function `_am_mysql_handle_pf_rules_do_single_query':
/usr/local/vpn-mysql/src/am_mysql.c:600: undefined reference to`mysql_query'
/usr/local/vpn-mysql/src/am_mysql.c:604: undefined reference to `mysql_error'
/usr/local/vpn-mysql/src/am_mysql.c:604: undefined reference to`mysql_errno'
/usr/local/vpn-mysql/src/am_mysql.c:608: undefined reference to `mysql_store_result'
/usr/local/vpn-mysql/src/am_mysql.c:626: undefined reference to`mysql_num_rows'
/usr/local/vpn-mysql/src/am_mysql.c:684: undefined reference to `mysql_free_result'
/usr/local/vpn-mysql/src/am_mysql.c:639: undefined reference to`mysql_num_fields'
/usr/local/vpn-mysql/src/am_mysql.c:616: undefined reference to `mysql_field_count'
/usr/local/vpn-mysql/src/am_mysql.c:622: undefined reference to`mysql_error'
/usr/local/vpn-mysql/src/am_mysql.c:622: undefined reference to `mysql_errno'
/usr/local/vpn-mysql/src/am_mysql.c:645: undefined reference to`mysql_fetch_row'
/usr/local/vpn-mysql/src/am_mysql.c:652: undefined reference to `mysql_fetch_lengths'
/usr/local/vpn-mysql/src/am_mysql.c:649: undefined reference to`mysql_error'
/usr/local/vpn-mysql/src/am_mysql.c:649: undefined reference to `mysql_errno'
../src/.libs/libopenvpn-mysql-auth.a(am_mysql.o): In function`am_mysql_handle_auth_user_pass_verify':
/usr/local/vpn-mysql/src/am_mysql.c:837: undefined reference to `mysql_close'
/usr/local/vpn-mysql/src/am_mysql.c:837: undefined reference to`mysql_close'
/usr/local/vpn-mysql/src/am_mysql.c:837: undefined reference to `mysql_close'
../src/.libs/libopenvpn-mysql-auth.a(am_mysql.o): In function`am_mysql_query_return_row_0':
/usr/local/vpn-mysql/src/am_mysql.c:383: undefined reference to `mysql_close'
/usr/local/vpn-mysql/src/am_mysql.c:383: undefined reference to`mysql_close'
../src/.libs/libopenvpn-mysql-auth.a(am_mysql.o):/usr/local/vpn-mysql/src/am_mysql.c:268: more undefined references to `mysql_close' follow
../src/.libs/libopenvpn-mysql-auth.a(am_mysql.o): In function`am_mysql_library_end':
/usr/local/vpn-mysql/src/am_mysql.c:851: undefined reference to `mysql_server_end'
../src/.libs/libopenvpn-mysql-auth.a(am_mysql.o): In function`am_mysql_library_init':
/usr/local/vpn-mysql/src/am_mysql.c:846: undefined reference to `mysql_server_init'
collect2: ld returned 1 exit status
make[2]: *** [testplugin] Error 1
make[2]: Leaving directory`/usr/local/vpn-mysql/tests'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/vpn-mysql'
make: **\* [all] Error 2

**Comment by chantra** [comment]
pacochair,

do you have mysql headers installed?

**Comment by pacochair** [comment]
Can you give me more details? What should I do you install mysql header?
Many thx.

**Comment by pacochair** [comment]
Actually, when I ran the ./autogen.sh it pass, however, when ./configure
It got the error saying m4 directory is missing.

checking how to hardcode library paths into programs... immediate
appending configuration tag "F77" to libtool
configure: error: cannot find macro directory `m4'

when I mkdir m4, it is OK again. May I know if it is normal?

I have libtool in the box. no idea about the mysql 

[root@fst01 chantra-openvpn-mysql-auth-5f38521]# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for style of include used by make... GNU
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking dependency style of gcc... gcc3
checking dependency style of gcc... (cached) gcc3
checking for a sed that does not truncate output... /bin/sed
checking for egrep... grep -E
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognise dependent libraries... pass_all
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking dependency style of g++... (cached) gcc3
checking how to run the C++ preprocessor... g++ -E
checking for g77... no
checking for f77... no
checking for xlf... no
checking for frt... no
checking for pgf77... no
checking for fort77... no
checking for fl32... no
checking for af77... no
checking for f90... no
checking for xlf90... no
checking for pgf90... no
checking for epcf90... no
checking for f95... no
checking for fort... no
checking for xlf95... no
checking for ifc... no
checking for efc... no
checking for pgf95... no
checking for lf95... no
checking for gfortran... no
checking whether we are using the GNU Fortran 77 compiler... no
checking whether  accepts -g... no
checking the maximum length of command line arguments... 32768
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC
checking if gcc PIC flag -fPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
configure: creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC
checking if g++ PIC flag -fPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
appending configuration tag "F77" to libtool
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ANSI C... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking dependency style of gcc... (cached) gcc3
checking mysql/mysql.h usability... yes
checking mysql/mysql.h presence... yes
checking for mysql/mysql.h... yes
checking for mysql_init in -lmysqlclient... no
checking for a BSD-compatible install... /usr/bin/install -c
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

From the ./configure output, it seems I have.

Thanks,

**Comment by pacochair** [comment]
additionally, mysql is running well there. I have problem in compiling. Thanks for your kindly assistant.

**Comment by chantra** [comment]
it fails at checking mysql_init in lmysqlclient.
as per the readme you need MySQL client library. it depends on the distribution you use. the lib name in readme is for debian based system. influence red hat based, it will have a different name.

**Comment by pacochair** [comment]
[root@localhost ld.so.conf.d]# ls
mysql-i386.conf  qt-i386.conf  xulrunner-32.conf
[root@localhost ld.so.conf.d]# cat mysql-i386.conf
/usr/lib/mysql
[root@localhost ld.so.conf.d]# cd /usr/lib/mysql/
[root@localhost mysql]# ll
total 8336
-rw-r--r-- 1 root root    1498 May 10 06:21 libdbug.a
-rw-r--r-- 1 root root   50704 May 10 06:21 libheap.a
-rw-r--r-- 1 root root  378224 May 10 06:21 libmyisam.a
-rw-r--r-- 1 root root   30730 May 10 06:21 libmyisammrg.a
-rw-r--r-- 1 root root 1640064 May 10 06:21 libmysqlclient.a
-rw-r--r-- 1 root root 1652652 May 10 06:21 libmysqlclient_r.a
lrwxrwxrwx 1 root root      26 May 27 00:52 libmysqlclient_r.so -> libmysqlclient_r.so.15.0.0
lrwxrwxrwx 1 root root      26 May 27 00:51 libmysqlclient_r.so.15 -> libmysqlclient_r.so.15.0.0
-rwxr-xr-x 1 root root 1462820 May 10 06:21 libmysqlclient_r.so.15.0.0
lrwxrwxrwx 1 root root      24 May 27 00:52 libmysqlclient.so -> libmysqlclient.so.15.0.0
lrwxrwxrwx 1 root root      24 May 27 00:51 libmysqlclient.so.15 -> libmysqlclient.so.15.0.0
-rwxr-xr-x 1 root root 1451932 May 10 06:21 libmysqlclient.so.15.0.0
-rw-r--r-- 1 root root 1368506 May 10 06:21 libmystrings.a
-rw-r--r-- 1 root root  330274 May 10 06:21 libmysys.a
-rw-r--r-- 1 root root   14312 May 10 06:21 libvio.a
-rwxr-xr-x 1 root root   13169 May 10 06:21 mysqlbug
-rwxr-xr-x 1 root root    6215 May 10 06:21 mysql_config

still don't know what to do, it seems that the file is there but cannot be identified.

**Comment by chantra** [comment]
i dont know, it compile just fine for me on debian based linuxes.

Can you tell me what OS you are running pls.

**Comment by pacochair** [comment]
Thanks for your help and quick response.
Just like to know if anyone experience the same problem before and see if they have solution or idea about the situation.
What I have tried is on a physical machine and two vm, all failed.

**Comment by pacochair** [comment]
all are Intel 32bit processors

**Comment by pacochair** [comment]
Centos

**Comment by chantra** [comment]
A quick fix would be to add a symlink to /usr/lib/mysql/libmysqlclient.so:

```
ln -s /usr/lib/mysql/libmysqlclient.so /usr/lib/libmysqlclient.so
```

That should get you sorted. I dont really know why AC_CHECK_LIB doesn't pick it up from /usr/lib/mysql

**Comment by pacochair** [comment]
thx, it works!
