### ISSUE TITLE
could not load plugin shared object

### ISSUE THREAD

**Issue by pacochair** [chantra/openvpn-mysql-auth#2]
Hello Chantra,

After I compile the so, I start the openvpn server with everything configured accordingly. However, it failed to start and the log is below.

I have seen this when I compile pam_mysql. It also got undefined symbol. Could you tell me why is it happen and any solution?

Many thanks,

[root@localhost auth-conf]# cat auth-openvpn.log
Mon May 30 17:54:18 2011 us=163637 PLUGIN_INIT: could not load plugin shared object /usr/local/openvpn/keys/libopenvpn-mysql-auth.so: /usr/local/openvpn/keys/libopenvpn-mysql-auth.so: undefined symbol: mysql_options
Mon May 30 17:54:18 2011 us=163776 Exiting
[root@localhost auth-conf]# ldd -r /usr/local/openvpn/keys/libopenvpn-mysql-auth.so
undefined symbol: mysql_options (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_query   (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_num_fields      (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
        linux-gate.so.1 =>  (0x0049e000)
        libc.so.6 => /lib/libc.so.6 (0x004e6000)
        /lib/ld-linux.so.2 (0x00276000)
undefined symbol: mysql_field_count     (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_server_end      (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_init    (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_fetch_row       (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_close   (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_real_connect    (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_fetch_lengths   (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_server_init     (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_affected_rows   (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_error   (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_num_rows        (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_store_result    (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_real_escape_string      (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_errno   (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)
undefined symbol: mysql_free_result     (/usr/local/openvpn/keys/libopenvpn-mysql-auth.so)

**Comment by pacochair** [comment]
The above stuffs are in Centos box.

I have already finish the compilation in Debian box. It is very OK without any problem.

Many thanks,

**Comment by clarkn** [comment]
Hi, I was able to get it to work on CentOS 5.6 by doing the following:
1. Create the m4 directory when it complains about it missing:  mkdir m4
2. Create the symbolic link for libmysql: ln -s /usr/lib/mysql/libmysqlclient.so /usr/lib/libmysqlclient.so
3. To overcome the "undefined mysql_options" problem, comment out the clause in src/am_mysql.c:
   /\* Potentially try to read group options if any are set _/
       /_if (mysql_options(mysql, MYSQL_READ_DEFAULT_GROUP, "openvpn-mysql-auth") != 0){
               LOGWARNING ("Could not read options for group _openvpn-mysql-auth_\n");
       }*/

**Comment by pacochair** [comment]
Another way to make it work on Centos 5.6

[root@cen-cl chantra-openvpn-mysql-auth-5f38521]#yum install mysql-server.i386 mysql-devel.i386 mysql.i386 libtool
[root@cen-cl chantra-openvpn-mysql-auth-5f38521]#ln -s /usr/lib/mysql/libmysqlclient.so /usr/lib/libmysqlclient.so 
[root@cen-cl chantra-openvpn-mysql-auth-5f38521]#mkdir m4

Verification:
[root@cen-cl chantra-openvpn-mysql-auth-5f38521]# ldd -r src/.libs/libopenvpn-mysql-auth.so
        linux-gate.so.1 =>  (0x00fee000)
        libmysqlclient.so.15 => /usr/lib/mysql/libmysqlclient.so.15 (0x00c21000)
        libc.so.6 => /lib/libc.so.6 (0x0024c000)
        libcrypt.so.1 => /lib/libcrypt.so.1 (0x00186000)
        libnsl.so.1 => /lib/libnsl.so.1 (0x00110000)
        libm.so.6 => /lib/libm.so.6 (0x00da1000)
        libssl.so.6 => /lib/libssl.so.6 (0x00e1d000)
        libcrypto.so.6 => /lib/libcrypto.so.6 (0x0044a000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00693000)
        /lib/ld-linux.so.2 (0x0022f000)
        libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x00129000)
        libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x00b09000)
        libcom_err.so.2 => /lib/libcom_err.so.2 (0x00727000)
        libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x00f0e000)
        libresolv.so.2 => /lib/libresolv.so.2 (0x00deb000)
        libdl.so.2 => /lib/libdl.so.2 (0x00157000)
        libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x0015c000)
        libkeyutils.so.1 => /lib/libkeyutils.so.1 (0x0064d000)
        libselinux.so.1 => /lib/libselinux.so.1 (0x00165000)
        libsepol.so.1 => /lib/libsepol.so.1 (0x00597000)

**Comment by Aleks305** [comment]
Hello Chantra!
Please tell me, can i use openvpn-mysql-auth on Centos 6.3 x86_64. I have the same error,when I try to use plugin:
[root@km35024-01 openvpn]# ldd -r /etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so
undefined symbol: mysql_options (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_query   (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_num_fields      (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
        linux-vdso.so.1 =>  (0x00007fff61bfe000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fce88e21000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fce893c7000)
undefined symbol: mysql_field_count     (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_server_end      (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_init    (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_fetch_row       (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_close   (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_real_connect    (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_fetch_lengths   (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_server_init     (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_affected_rows   (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_error   (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_num_rows        (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_store_result    (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_real_escape_string      (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_errno   (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)
undefined symbol: mysql_free_result     (/etc/openvpn/mysql-auth/libopenvpn-mysql-auth.so)

I tryed to add symbolic links:
 [root@km35024-01 openvpn]# ls -l /usr/lib64/libmysqlclient.so
lrwxrwxrwx 1 root root 34 Sep  6 12:43 /usr/lib64/libmysqlclient.so -> /usr/lib64/mysql/libmysqlclient.so

[root@km35024-01 openvpn]# ls -l /usr/lib/libmysqlclient.so
lrwxrwxrwx 1 root root 32 Sep  6 15:00 /usr/lib/libmysqlclient.so -> /usr/lib/mysql/libmysqlclient.so

But this not helped to me...
Please, help.

**Comment by Aleks305** [comment]
I'm sorry.
I forgeted about this:
To overcome the "undefined mysql_options" problem, comment out the clause in src/am_mysql.c:
/\* Potentially try to read group options if any are set /
/_if (mysql_options(mysql, MYSQL_READ_DEFAULT_GROUP, "openvpn-mysql-auth") != 0){
LOGWARNING ("Could not read options for group *openvpn-mysql-auth\n");
}_/

**Comment by chantra** [comment]
It has been a long time since I look at this plugin. It works just fine for me on Debian Wheezy 7 .
I will try to find some time to get it working on both centos and debian

**Comment by chantra** [comment]
@Aleks305 
I have just pushed commit 8071484a0bc39 which I believe should help.

Would you mind pulling the latest version and confirming you can install and run the plugin.
tks

**Comment by Aleks305** [comment]
hello!
Thank you for you replyes! i downloades latest version, installed and ran plugin.
It works very well!

**Comment by chantra** [comment]
noce to hear. I also just provisionned a centos 64 6.X box and could get things up with no issues. closing this.
