### ISSUE TITLE
Can't compile on debian 7

### ISSUE THREAD

**Issue by oferreiro** [chantra/openvpn-mysql-auth#4]
I can not compile on latest debian and ubuntu.
Both uses mysql 5.5 and libtool  2.4.2.

On make:
am_mysql.c: In function 'create_expandable_variable_list':
am_mysql.c:96:41: error: variable 'escaped_password_length' set but not used [-Werror=unused-but-set-variable]
  unsigned long escaped_username_length, escaped_password_length;
                                         ^
am_mysql.c:96:16: error: variable 'escaped_username_length' set but not used [-Werror=unused-but-set-variable]
  unsigned long escaped_username_length, escaped_password_length;

I can compile after manually remove -Werror from compile command. 
Like this:
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/include/mysql -DBIG_JOINS=1  -fno-strict-aliasing   -g -DNDEBUG  -g -O2 -g -Wall -MT libopenvpn_mysql_auth_la-am_mysql.lo -MD -MP -MF .deps/libopenvpn_mysql_auth_la-am_mysql.Tpo -c -o libopenvpn_mysql_auth_la-am_mysql.lo `test -f 'am_mysql.c' || echo './'`am_mysql.c

I receive this:
am_mysql.c: In function 'create_expandable_variable_list':
am_mysql.c:96:41: warning: variable 'escaped_password_length' set but not used [-Wunused-but-set-variable]
  unsigned long escaped_username_length, escaped_password_length;
                                         ^
am_mysql.c:96:16: warning: variable 'escaped_username_length' set but not used [-Wunused-but-set-variable]
  unsigned long escaped_username_length, escaped_password_length;

After that, if I try make again, libtool link libs without error.
Apparently binary libs are working.

**Comment by babatonga** [comment]
Same error here. Did anybody found a solution?

**Comment by chantra** [comment]
I did not get a chance to look at this yet. I will once my vacations are over.

**Comment by chantra** [comment]
This should be fixed in 7f4a33e3a661dbd994253a10bb747634fc72f1f6

**Comment by oferreiro** [comment]
Thank you…
